(() => {
  "use strict";

  const RUN_SECONDS = 60;
  const resourceTypes = {
    food: { color: "#99ffcc", label: "Food" },
    energy: { color: "#6ff8ff", label: "Energy" },
    material: { color: "#c77dff", label: "Material" }
  };
  const canvas = document.querySelector("#colonyCanvas");
  if (!canvas) return;
  const ctx = canvas.getContext("2d");
  const prefersReducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const ui = {
    start: document.querySelector("#startRun"), reset: document.querySelector("#resetRun"), time: document.querySelector("#timeRemaining"),
    resources: document.querySelector("#resourceReadout"), objective: document.querySelector("#liveObjective"), feed: document.querySelector("#eventFeed"),
    empty: document.querySelector("#dashboardEmpty"), dashboard: document.querySelector("#dashboard"), kpis: document.querySelector("#kpiGrid"), mix: document.querySelector("#mixBar"),
    growth: document.querySelector("#growthChart"), allocation: document.querySelector("#allocationChart"), heatmap: document.querySelector("#heatmap"),
    insights: document.querySelector("#insights"), leaderboard: document.querySelector("#leaderboard"), recent: document.querySelector("#recentRuns")
  };

  let state;
  const makeState = () => ({ running: false, ended: false, startedAt: null, elapsed: 0, lastTick: performance.now(), colony: { x: 450, y: 280, level: 1, radius: 34 },
    resources: { food: 0, energy: 0, material: 0 }, totalResources: 0, workersCreated: 4, expansionCount: 0, clicks: 0, idleSeconds: 0, wastedMovement: 0,
    workers: Array.from({ length: 4 }, (_, i) => ({ id: i + 1, x: 450, y: 280, target: null, carrying: null, outbound: false, busy: false, distance: 0 })),
    nodes: [], events: [], particles: [], heat: Array(12 * 8).fill(0), resourceTimeline: [], workerAllocation: [], lastHazardSecond: 0 });

  const rand = (min, max) => min + Math.random() * (max - min);
  const dist = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  const addEvent = (message) => { state.events.unshift({ t: Math.round(state.elapsed), message }); ui.feed.innerHTML = state.events.slice(0, 5).map(e => `<li>${e.t}s · ${e.message}</li>`).join(""); };
  const spawnNode = () => {
    const type = Object.keys(resourceTypes)[Math.floor(Math.random() * 3)];
    const angle = rand(0, Math.PI * 2), radius = rand(115, 360);
    state.nodes.push({ id: crypto.randomUUID(), type, x: state.colony.x + Math.cos(angle) * radius, y: state.colony.y + Math.sin(angle) * radius, amount: Math.round(rand(16, 34)), decay: rand(.45, .9), hazard: 0, pulse: rand(0, 10) });
  };
  const reset = () => { state = makeState(); for (let i = 0; i < 8; i++) spawnNode(); updateReadout(); ui.time.textContent = RUN_SECONDS; ui.objective.textContent = "Start the run, then click resource nodes. Idle workers automatically wait at the hive."; ui.feed.innerHTML = "<li>Hazards will appear during the run.</li>"; draw(); };

  const updateReadout = () => { ui.resources.innerHTML = Object.entries(resourceTypes).map(([key, meta]) => `<div class="resource-chip"><span>${meta.label}</span><strong style="color:${meta.color}">${Math.floor(state.resources[key])}</strong></div>`).join("") + `<div class="resource-chip"><span>Workers</span><strong>${state.workers.length}</strong></div><div class="resource-chip"><span>Colony level</span><strong>${state.colony.level}</strong></div>`; };
  const assignWorker = (node) => { const worker = state.workers.find(w => !w.busy); state.clicks++; if (!worker) { addEvent("All workers are committed; click again when one returns."); return; } worker.target = node; worker.outbound = true; worker.busy = true; worker.distance = dist(worker, node); addEvent(`Worker assigned to ${resourceTypes[node.type].label.toLowerCase()} node.`); };
  canvas.addEventListener("click", (event) => { if (!state.running) return; const rect = canvas.getBoundingClientRect(); const point = { x: (event.clientX - rect.left) * canvas.width / rect.width, y: (event.clientY - rect.top) * canvas.height / rect.height }; const node = state.nodes.find(n => dist(point, n) < 26); if (node) assignWorker(node); });

  const maybeExpand = () => { const cost = 32 + state.colony.level * 18; if (state.totalResources >= cost * state.colony.level && state.colony.level < 8) { state.colony.level++; state.colony.radius += 5; state.expansionCount++; addEvent(`Hive expanded to level ${state.colony.level}.`); } if (state.totalResources > state.workers.length * 13 && state.workers.length < 18) { state.workers.push({ id: state.workers.length + 1, x: state.colony.x, y: state.colony.y, target: null, carrying: null, outbound: false, busy: false, distance: 0 }); state.workersCreated++; addEvent("A new worker emerged from stored resources."); } };
  const snapshot = () => { state.resourceTimeline.push({ t: Math.round(state.elapsed), total: Math.round(state.totalResources), ...state.resources }); const alloc = { idle: 0, food: 0, energy: 0, material: 0 }; state.workers.forEach(w => alloc[w.target?.type || "idle"]++); state.workerAllocation.push({ t: Math.round(state.elapsed), ...alloc }); };
  const tick = (now) => { const dt = Math.min(.08, (now - state.lastTick) / 1000); state.lastTick = now; if (state.running) { state.elapsed += dt; ui.time.textContent = Math.max(0, Math.ceil(RUN_SECONDS - state.elapsed)); state.nodes.forEach(n => { n.amount -= n.decay * dt; n.pulse += dt; }); state.nodes = state.nodes.filter(n => n.amount > 1); if (state.nodes.length < 8) spawnNode(); const hazardSecond = Math.floor(state.elapsed); if (hazardSecond >= 15 && hazardSecond % 15 === 0 && hazardSecond !== state.lastHazardSecond) { state.lastHazardSecond = hazardSecond; const n = state.nodes[Math.floor(Math.random() * state.nodes.length)]; if (n) { n.hazard = 5; n.decay *= 2.1; addEvent("Solar flare accelerated decay on a remote node."); } } let idle = 0; state.workers.forEach(w => { if (!w.busy) { idle += dt; return; } const target = w.outbound ? w.target : state.colony; const speed = prefersReducedMotion ? 110 : 150; const d = dist(w, target); if (d < 5) { if (w.outbound) { w.carrying = { type: w.target.type, amount: Math.min(8, w.target.amount) }; w.target.amount -= w.carrying.amount; w.outbound = false; } else { state.resources[w.carrying.type] += w.carrying.amount; state.totalResources += w.carrying.amount; w.busy = false; w.target = null; w.carrying = null; maybeExpand(); } } else { w.x += ((target.x - w.x) / d) * speed * dt; w.y += ((target.y - w.y) / d) * speed * dt; const gx = Math.max(0, Math.min(11, Math.floor(w.x / canvas.width * 12))); const gy = Math.max(0, Math.min(7, Math.floor(w.y / canvas.height * 8))); state.heat[gy * 12 + gx] += dt; if (w.distance > 280) state.wastedMovement += dt * .28; } }); state.idleSeconds += idle; if (Math.floor(state.elapsed) !== Math.floor(state.elapsed - dt) && Math.floor(state.elapsed) % 5 === 0) snapshot(); updateReadout(); if (state.elapsed >= RUN_SECONDS) endRun(); } draw(); requestAnimationFrame(tick); };

  const drawHex = (x, y, r, color) => { ctx.beginPath(); for (let i = 0; i < 6; i++) { const a = Math.PI / 6 + i * Math.PI / 3; ctx[i ? "lineTo" : "moveTo"](x + Math.cos(a) * r, y + Math.sin(a) * r); } ctx.closePath(); ctx.strokeStyle = color; ctx.stroke(); };
  const draw = () => { ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "rgba(111,248,255,.08)"; for (let x = 0; x < canvas.width; x += 60) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke(); } for (let y = 0; y < canvas.height; y += 60) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); ctx.stroke(); } drawHex(state.colony.x, state.colony.y, state.colony.radius, "rgba(111,248,255,.9)"); ctx.fillStyle = "rgba(111,248,255,.16)"; ctx.beginPath(); ctx.arc(state.colony.x, state.colony.y, state.colony.radius, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#f6f7ff"; ctx.fillText(`L${state.colony.level}`, state.colony.x - 7, state.colony.y + 4); state.nodes.forEach(n => { const meta = resourceTypes[n.type]; ctx.strokeStyle = meta.color; ctx.fillStyle = meta.color; drawHex(n.x, n.y, 13 + Math.sin(n.pulse * 3) * 2, meta.color); ctx.globalAlpha = .18; ctx.beginPath(); ctx.arc(n.x, n.y, 22 + n.hazard * 2, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; ctx.fillText(Math.round(n.amount), n.x - 8, n.y - 20); }); state.workers.forEach(w => { if (w.target) { ctx.strokeStyle = "rgba(255,255,255,.14)"; ctx.beginPath(); ctx.moveTo(w.x, w.y); ctx.lineTo((w.outbound ? w.target : state.colony).x, (w.outbound ? w.target : state.colony).y); ctx.stroke(); } ctx.fillStyle = w.carrying ? resourceTypes[w.carrying.type].color : "#ffffff"; ctx.beginPath(); ctx.arc(w.x, w.y, 5, 0, Math.PI * 2); ctx.fill(); }); };

  const lineChart = (target, series, keys) => { const c = target, x = c.getContext("2d"), pad = 28; x.clearRect(0,0,c.width,c.height); x.strokeStyle="rgba(255,255,255,.12)"; x.strokeRect(pad,pad,c.width-pad*1.5,c.height-pad*1.7); const max = Math.max(1, ...series.flatMap(p => keys.map(k => p[k] || 0))); keys.forEach((k, i) => { x.strokeStyle = resourceTypes[k]?.color || ["#6ff8ff", "#c77dff", "#99ffcc", "#ff66d8"][i]; x.beginPath(); series.forEach((p, idx) => { const px = pad + idx / Math.max(1, series.length - 1) * (c.width - pad * 1.8); const py = c.height - pad - ((p[k] || 0) / max) * (c.height - pad * 2); x[idx ? "lineTo" : "moveTo"](px, py); }); x.stroke(); }); };
  const endRun = async () => { state.running = false; state.ended = true; snapshot(); const endedAt = new Date(); const efficiencyScore = Math.max(1, Math.min(99, Math.round((state.totalResources / 2.25) - state.wastedMovement - state.idleSeconds / 18 + state.colony.level * 6))); const run = { runId: crypto.randomUUID(), startedAt: state.startedAt.toISOString(), endedAt: endedAt.toISOString(), durationSeconds: RUN_SECONDS, resourcesCollected: Object.fromEntries(Object.entries(state.resources).map(([k,v]) => [k, Math.round(v)])), totalResources: Math.round(state.totalResources), workersCreated: state.workersCreated, colonyLevel: state.colony.level, expansionCount: state.expansionCount, efficiencyScore, clicks: state.clicks, actions: state.clicks, idleSeconds: Math.round(state.idleSeconds), wastedMovement: Math.round(state.wastedMovement), eventLog: state.events.slice().reverse(), resourceTimeline: state.resourceTimeline, workerAllocation: state.workerAllocation, heat: state.heat }; localStorage.setItem("colonyOpsRuns", JSON.stringify([run, ...JSON.parse(localStorage.getItem("colonyOpsRuns") || "[]")].slice(0, 5))); renderDashboard(run); };
  const renderDashboard = async (run) => { ui.empty.hidden = true; ui.dashboard.hidden = false; ui.kpis.innerHTML = [["Final score", run.totalResources], ["Efficiency", `${run.efficiencyScore}%`], ["Total resources", run.totalResources], ["Colony level", run.colonyLevel]].map(([a,b]) => `<article class="kpi-card"><span>${a}</span><strong>${b}</strong></article>`).join(""); const total = Math.max(1, run.totalResources); ui.mix.innerHTML = Object.entries(resourceTypes).map(([k,m]) => { const pct = Math.round((run.resourcesCollected[k] || 0) / total * 100); return `<div class="mix-row"><span>${m.label}</span><div class="mix-track"><div class="mix-fill" style="width:${pct}%;background:${m.color};color:${m.color}"></div></div><strong>${pct}%</strong></div>`; }).join(""); lineChart(ui.growth, run.resourceTimeline, ["total", "food", "energy", "material"]); lineChart(ui.allocation, run.workerAllocation, ["idle", "food", "energy", "material"]); const heatMax = Math.max(1, ...run.heat); ui.heatmap.innerHTML = run.heat.map(v => `<span class="heat-cell" style="--heat:${(v / heatMax).toFixed(2)}"></span>`).join(""); const best = Object.entries(run.resourcesCollected).sort((a,b)=>b[1]-a[1])[0][0]; ui.insights.innerHTML = `<li>Your strongest stream was ${resourceTypes[best].label.toLowerCase()}, shaping ${Math.round(run.resourcesCollected[best]/total*100)}% of the colony mix.</li><li>${run.idleSeconds > 90 ? "Worker idle time was high; dispatch earlier and keep routes short." : "Worker utilization stayed healthy for a lightweight simulation run."}</li><li>${run.efficiencyScore >= 80 ? "You outperformed the benchmark efficiency band." : "Try prioritizing closer nodes to reduce wasted movement."}</li>`; const samples = await fetch("/data/colony-sample-runs.json").then(r => r.json()).catch(() => []); const ranked = [...samples, { name: "Your run", ...run, current: true }].sort((a,b)=>b.totalResources-a.totalResources); const percentile = Math.round(samples.filter(s => s.totalResources <= run.totalResources).length / Math.max(1, samples.length) * 100); ui.leaderboard.innerHTML = `<p class="fine-print">Your resource score is at the ${percentile}th percentile of the mock benchmark set.</p>` + ranked.slice(0, 9).map((r,i)=>`<div class="board-row ${r.current ? "current" : ""}"><span>#${i+1}</span><strong>${r.name}</strong><span>${r.totalResources} · ${r.efficiencyScore}%</span></div>`).join(""); ui.recent.innerHTML = JSON.parse(localStorage.getItem("colonyOpsRuns") || "[]").map((r,i)=>`<div class="board-row"><span>${i+1}</span><strong>${new Date(r.endedAt).toLocaleTimeString()}</strong><span>${r.totalResources} · L${r.colonyLevel}</span></div>`).join(""); };

  ui.start.addEventListener("click", () => { reset(); state.running = true; state.startedAt = new Date(); state.lastTick = performance.now(); ui.objective.textContent = "Click resource nodes to dispatch idle workers. Balance nearby resources for a high efficiency score."; addEvent("Run started."); });
  ui.reset.addEventListener("click", reset);
  reset(); requestAnimationFrame(tick);
})();
